<?php
//////////////////////////////////////
// MailMain Index Page              //
//////////////////////////////////////

//////////////////////////////////////
//    DO NOT EDIT THIS FILE!!!      //
//////////////////////////////////////

require "classes.php";

//Brings in item to check operating system
require "scripts/osCheck.php";

//Checks to see if postfix is imstalled
//Will later check for dovecot
require "scripts/applicationCheck.php";

//Checks to see if the runas.sh script is present on the computer
//Will later check for the integrety
require "scripts/runAsCheck.php";

//Runs initial setup if first time running MailMan
require "scripts/initialSetup.php";

?>